"""empty message

Revision ID: 513f8cb6eb05
Revises: 3d3db2a12a28
Create Date: 2021-05-11 23:15:47.682557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513f8cb6eb05'
down_revision = '3d3db2a12a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('phone', sa.String(length=17), nullable=False))
    op.create_unique_constraint(None, 'user', ['last_name'])
    op.create_unique_constraint(None, 'user', ['name'])
    op.drop_column('user', 'username')
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=150), nullable=False))
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=256), nullable=False))
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
